### ISSUE TITLE
Footer qui n'est pas collé en bas de page

### ISSUE THREAD

**Issue by valentinp72** [valentinp72/projetWebD#3]

**Comment by TitouanT** [comment]
la valeur par défaut de position est static, c'est celle dont on a besoin pour le footer.

**Comment by valentinp72** [comment]
Ça marche sur des pages avec du contenu, mais sur des petites pages, ou quand l'écran est grand niveau hauteur, ça déconne. J'étais en train de travailler dessus, je viens de trouver comment faire, et aussi comment résoudre le contenu du footer qui s'affiche mal sur des petits écrans. 😀
